### ISSUE TITLE
[Refactor] 나의 전략 일간 분석 조회 페이지 권한 추가 및 리팩토링

### ISSUE THREAD

**Issue by kbyunghoon** [FC-DEV-FinalProject/FinalProject_team3_BE#142]
## 🔧 어떤 기능인가요?

> 일간 분석 조회 페이지 권한 추가 및 리팩토링

## ✏️ 작업 상세 내용

- [ ] 일간 분석 조회 페이지 권한 추가
- [ ] 예외처리 추가
- [ ] 리팩토링

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added @PreAuthorize annotation to restrict access to daily analysis endpoint. Implemented exception handling for invalid strategy ID and unauthorized access. Refactored the code to use Optional for better null handling.

You can review changes in this commit: https://github.com/mnmnk43434/FC-DEV-FinalProject-FinalProject_team3_BE-142/commit/14eccc7629aa9e40b59c487a4b3c000903c99fc4.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
